sudo: false
language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "pypy3"

arch:
  - amd64
  - ppc64le

env:
  - DJANGO="django==3.0.7"
  - DJANGO="django==2.2.8"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install pycodestyle
  - pip install flake8
  - pip install coveralls

before_script:
  - "pycodestyle --exclude=migrations,tests --ignore=E501,E241,E225,E128 ."
  - "flake8 --exclude=migrations,tests --ignore=E501,E241,E225,E128 ."

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django==3.0.7"
    - python: "pypy3"
      arch: ppc64le


script: coverage run --source=ipware manage.py test

after_success:
  coveralls

